export default {
  products: [
    {
      _id: "1",
      name: "Beer big",
      category: "Black",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "2",
      name: "Beer big",
      category: "Lager",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "3",
      name: "Beer big",
      category: "Lager",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "4",
      name: "Beer sota",
      category: "Lager",
      image: "/images/d1.jpg",
      price: 70,
      brand: "Nike",
      rating: 1.5,
      numReviews: 145,
    },
    {
      _id: "5",
      name: "Beer big",
      category: "Lager",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
  ],
};
